# Generated by Django 6.1.1 on 2026-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_batch_submittedurl_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittedurl',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submittedurl',
            name='extracted_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submittedurl',
            name='extraction_method',
            field=models.CharField(choices=[('none', 'None'), ('static', 'Static'), ('browser', 'Browser')], default='none', max_length=16),
        ),
    ]
