# Generated by Django 6.1.1 on 2026-09-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submittedurl_extracted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='submissions.batch')),
                ('submitted_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='submissions.submittedurl')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('batch', 'submitted_url')},
            },
        ),
    ]
