# Generated by Django 6.1.1 on 2026-09-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_backfill_batchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='submissions.batch'),
        ),
    ]
