# Generated by Django 6.1.1 on 2026-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submittedurl_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='failure_kind',
            field=models.CharField(blank=True, choices=[('dns', 'DNS - host not found'), ('connection', 'Connection failed'), ('http_client', 'HTTP client error (4xx)'), ('blocked', 'Blocked / rate-limited (401/403/429)'), ('timeout', 'Timed out'), ('too_large', 'Response too large'), ('unsupported_type', 'Unsupported content type'), ('no_content', 'No extractable content'), ('unknown', 'Unknown / uncategorised')], default='', max_length=20),
        ),
    ]
