# Generated by Django 6.1.1 on 2026-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submittedurl_failure_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='extraction_method',
            field=models.CharField(choices=[('none', 'None'), ('static', 'Static'), ('browser', 'Browser'), ('document', 'Document')], default='none', max_length=16),
        ),
    ]
