# Generated by Django 6.1.1 on 2026-09-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_submittedurl_failure_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='generation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submittedurl',
            name='generation_status',
            field=models.CharField(blank=True, choices=[('', 'Not started'), ('ok', 'Cards generated'), ('failed', 'Failed to generate')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('basic', 'Basic (Q&A)'), ('cloze', 'Cloze')], max_length=8)),
                ('front', models.TextField()),
                ('back', models.TextField(blank=True, default='')),
                ('source_term', models.CharField(max_length=300)),
                ('tags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='submissions.batch')),
                ('submitted_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='submissions.submittedurl')),
            ],
            options={
                'ordering': ['submitted_url_id', 'id'],
            },
        ),
    ]
