# Generated by Django 6.1.1 on 2026-09-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_submittedurl_generation_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dedup_status',
            field=models.CharField(choices=[('unique', 'Unique'), ('duplicate', 'Duplicate')], default='unique', max_length=16),
        ),
        migrations.AddField(
            model_name='card',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='submissions.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
