# Generated by Django 6.1.1 on 2026-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_card_dedup_status_card_duplicate_of_card_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='review_status',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='undecided', max_length=16),
        ),
    ]
