# Generated by Django 6.1.1 on 2026-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_card_dedup_status_card_duplicate_of_card_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_source',
            field=models.CharField(choices=[('source_page', 'Source page'), ('draw_things', 'Draw Things'), ('none', 'None')], default='none', max_length=16),
        ),
    ]
