# Generated by Django 6.1.1 on 2026-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_card_rejection_reason_card_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='anki_note_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
