# Generated by Django 6.1.1 on 2026-09-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_card_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('basic', 'Basic (Q&A)'), ('cloze', 'Cloze')], max_length=8)),
                ('front', models.TextField()),
                ('back', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='', max_length=2000)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
