# Generated by Django 6.1.1 on 2026-09-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_card_anki_note_id_card_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='failure_kind',
            field=models.CharField(blank=True, choices=[('dns', 'DNS - host not found'), ('connection', 'Connection failed'), ('http_client', 'HTTP client error (4xx)'), ('blocked', 'Blocked / rate-limited (401/403/429)'), ('blocked_by_robots', 'Disallowed by robots.txt'), ('retries_exhausted', 'Retries exhausted'), ('timeout', 'Timed out'), ('too_large', 'Response too large'), ('unsupported_type', 'Unsupported content type'), ('no_content', 'No extractable content'), ('paywall', 'Paywall - subscription required'), ('bot_wall', 'Bot check / CAPTCHA'), ('consent_wall', 'Consent / cookie gate'), ('unknown', 'Unknown / uncategorised')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=16)),
                ('error_class', models.CharField(blank=True, default='', max_length=100)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='submissions.batch')),
                ('submitted_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='submissions.submittedurl')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
