# Generated by Django 6.1.1 on 2026-09-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_alter_submittedurl_failure_kind_llmcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_manually_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='original_back',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='original_front',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='original_image',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='original_image_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='feedback',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
    ]
