# Generated by Django 6.1.1 on 2026-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_card_edited_at_card_image_manually_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='extraction_method',
            field=models.CharField(choices=[('none', 'None'), ('static', 'Static'), ('browser', 'Browser'), ('document', 'Document'), ('ocr', 'OCR')], default='none', max_length=16),
        ),
    ]
