# Generated by Django 6.1.1 on 2026-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_alter_submittedurl_extraction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='extraction_method',
            field=models.CharField(choices=[('none', 'None'), ('static', 'Static'), ('browser', 'Browser'), ('document', 'Document'), ('ocr', 'OCR'), ('extension', 'Extension')], default='none', max_length=16),
        ),
    ]
