# Generated by Django 6.1.1 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_alter_submittedurl_extraction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='extension_image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
