# Generated by Django 6.1.1 on 2026-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_submittedurl_extension_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='deck_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
