# Generated by Django 6.1.1 on 2026-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_batch_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='dedup_ready',
            field=models.BooleanField(default=False),
        ),
    ]
