# Generated by Django 6.1.1 on 2026-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_submittedurl_dedup_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
