# Generated by Django 6.1.1 on 2026-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_llmcall_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='json_retried',
            field=models.BooleanField(default=False),
        ),
    ]
