# Generated by Django 6.1.1 on 2026-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0024_llmcall_json_retried'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedurl',
            name='llm_model_override',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submittedurl',
            name='llm_provider_override',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
