# Generated by Django 6.1.1 on 2026-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_submittedurl_llm_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='push_deck_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batch',
            name='push_failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='push_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='push_pushed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='push_skipped_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='push_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('unreachable', 'Unreachable')], default='', max_length=16),
        ),
    ]
