# Generated by Django 6.1.1 on 2026-09-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0027_alter_batch_push_status_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='dedup_status',
        ),
        migrations.RemoveField(
            model_name='card',
            name='duplicate_of',
        ),
        migrations.RemoveField(
            model_name='card',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='card',
            name='similarity_score',
        ),
        migrations.RemoveField(
            model_name='submittedurl',
            name='dedup_ready',
        ),
    ]
